### PR TITLE
Added Scroll to Top Button

### LINKED ISSUE #3: Add Scroll to Top Button
I would like to add Scroll to Top Button to add more interactivity for the users and we do not have to scroll back again and again. I can create  Scroll Button using HTML, CSS and JS. If you think that would be valuable feature kindly assign this issue to me. Thank You!

### PR DESCRIPTION
**Pull request by SattyamSamania**
I have Created Scroll to Top Button Using HTML, CSS and JS.

### CODE REVIEW

**Review by SattyamSamania — COMMENTED** [review]
I have added my HTML,CSS and JS code.

**Review by SattyamSamania — COMMENTED** [review]
I Have added HTML, CSS and JS code.

**Review by SattyamSamania — COMMENTED** [review]
I Have added my HTML, CSS and JS code in one file.

**Comment by SattyamSamania** [comment]
Hey @RahulSharma4329 Please review my PR. I am getting error for that.

**Review by RahulSharma4329 — APPROVED** [review]

**Pull request merged**
